# Multilayer Perceptrons for Time Series

DS-590 Spring 2022
Adapted from Jasoon Brownlee. 2021. Deep  Learning fro Time Series Forecasting

In [7]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

## Univariate Time Series

### Data Preparation

In [4]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [3]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

Step 1. Choose number of steps

Step 2. Split the univariate sequence

In [5]:
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


### MLP Model

- A simple MLP model has a single hidden layer of nodes, and an output layer used to make a prediction
- Keras is a Python library for developing and evaluating deep learning models

In [8]:
# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [11]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               400       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 501
Trainable params: 501
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
model.fit(X, y, epochs=2000, verbose=0)

### Prediction

The model expects the input shape to be two-dimensional with [samples, features]

In [14]:
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps))

In [16]:
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[100.60398]]


## Multivariate Time Series

### Parallel Time Series